package webhooks

import (
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/go-chi/chi/v5"

	"github.com/hazemarian/poor-man-cluster/pmcluster/internal/store"
)

// HTTP exposes webhook-source management over the Bearer-protected /api
// router. The shared HMAC secret is generated by the service, encrypted at
// rest, and returned to the caller ONCE on creation — listing a source never
// reveals its secret.
type HTTP struct {
	Svc Service
}

func (w *HTTP) Mount(r chi.Router) {
	r.Get("/webhooks", w.list)
	r.Post("/webhooks", w.create)
	r.Delete("/webhooks/{source}", w.remove)
	r.Get("/webhooks/{source}/deliveries", w.deliveries)
}

type webhookRow struct {
	Source      string `json:"source"`
	Description string `json:"description,omitempty"`
	CreatedAt   int64  `json:"created_at"`
	LastUsedAt  int64  `json:"last_used_at,omitempty"`
}

func (w *HTTP) list(res http.ResponseWriter, req *http.Request) {
	srcs, err := w.Svc.List(req.Context())
	if err != nil {
		writeErr(res, http.StatusInternalServerError, "list webhook sources: "+err.Error())
		return
	}
	rows := make([]webhookRow, 0, len(srcs))
	for _, s := range srcs {
		rows = append(rows, webhookRow(s))
	}
	writeJSON(res, http.StatusOK, map[string]any{"webhooks": rows})
}

type createWebhookRequest struct {
	Source      string `json:"source"`
	Description string `json:"description,omitempty"`
}

func (w *HTTP) create(res http.ResponseWriter, req *http.Request) {
	var body createWebhookRequest
	dec := json.NewDecoder(http.MaxBytesReader(res, req.Body, 1<<20))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&body); err != nil {
		writeErr(res, http.StatusBadRequest, "invalid JSON body: "+err.Error())
		return
	}
	source := strings.TrimSpace(body.Source)
	if source == "" {
		writeErr(res, http.StatusBadRequest, "source is required")
		return
	}

	secret, err := w.Svc.Create(req.Context(), source, body.Description)
	if err != nil {
		if errors.Is(err, store.ErrWebhookSourceExists) {
			writeErr(res, http.StatusConflict, "webhook source already exists: "+source)
			return
		}
		writeErr(res, http.StatusInternalServerError, "create webhook source: "+err.Error())
		return
	}

	writeJSON(res, http.StatusCreated, map[string]any{"source": source, "secret": secret})
}

func (w *HTTP) remove(res http.ResponseWriter, req *http.Request) {
	source := chi.URLParam(req, "source")
	if source == "" {
		writeErr(res, http.StatusBadRequest, "source is required")
		return
	}
	if err := w.Svc.Delete(req.Context(), source); err != nil {
		if errors.Is(err, store.ErrWebhookSourceNotFound) {
			writeErr(res, http.StatusNotFound, "webhook source not found: "+source)
			return
		}
		writeErr(res, http.StatusInternalServerError, "delete webhook source: "+err.Error())
		return
	}
	res.WriteHeader(http.StatusNoContent)
}

type deliveryRow struct {
	ID        int64  `json:"id"`
	Source    string `json:"source"`
	Status    string `json:"status"`
	StackName string `json:"stack_name,omitempty"`
	Revision  int64  `json:"revision,omitempty"`
	RepoURL   string `json:"repo_url,omitempty"`
	File      string `json:"file,omitempty"`
	Error     string `json:"error,omitempty"`
	CreatedAt int64  `json:"created_at"`
}

// deliveries returns delivery history for a source (newest first).
// Optional query param ?limit= clamps the result (default 50).
func (w *HTTP) deliveries(res http.ResponseWriter, req *http.Request) {
	source := chi.URLParam(req, "source")
	if source == "" {
		writeErr(res, http.StatusBadRequest, "source is required")
		return
	}
	limit := 50
	if v := req.URL.Query().Get("limit"); v != "" {
		if n, err := strconv.Atoi(v); err == nil && n > 0 && n <= 500 {
			limit = n
		}
	}
	ds, err := w.Svc.Deliveries(req.Context(), source, limit)
	if err != nil {
		writeErr(res, http.StatusInternalServerError, "list webhook deliveries: "+err.Error())
		return
	}
	rows := make([]deliveryRow, 0, len(ds))
	for _, d := range ds {
		rows = append(rows, deliveryRow(d))
	}
	writeJSON(res, http.StatusOK, map[string]any{"deliveries": rows})
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(body)
}

func writeErr(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]any{"error": msg})
}
