app: abbas
env: production
domain: nextrum-sy.com
registry: ghcr.io/nextrum-sy
version: v20260904-f059374

services:
  abbas:
    image: ${registry}/${app}:${version}
    placement: manager
    replicas: 1

    expose:
      port: 8080
      host: abbas.${domain}

    volumes:
      - abbas_data:/app/data

    env:
      PORT: "8080"
      DB_PATH: /app/data/abbas.db
      APP_ENV: production
      GIN_MODE: release
      AVAILABLE_LANGS: "en,ar"
      GOOGLE_CLIENT_ID: "188837913187-de8b6p0f0tpjd7mg4e3srh9eq9n54rnh.apps.googleusercontent.com"
      CREDIT_COST_PER_GEN: "0"

      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      OTEL_SERVICE_NAME: "abbas"

    secrets:
      - abbas_session_secret

    healthcheck:
      type: http
      path: /health
