package server

import (
	"database/sql"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/go-chi/chi/v5"

	"github.com/hazemarian/poor-man-stack/pmcluster/internal/service"
	"github.com/hazemarian/poor-man-stack/pmcluster/internal/store"
)

// APIKeyService exposes API-user (bearer token) management over the
// Bearer-protected /api router. The bearer token is generated by the service,
// hashed (argon2id) at rest, and returned to the caller ONCE on creation;
// listing users never reveals token material.
type APIKeyService struct {
	Svc service.APIKeysService
}

func (a *APIKeyService) Mount(r chi.Router) {
	r.Get("/api_keys", a.list)
	r.Post("/api_keys", a.create)
	r.Delete("/api_keys/{id}", a.remove)
}

type apiKeyRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

func (a *APIKeyService) list(res http.ResponseWriter, req *http.Request) {
	users, err := a.Svc.List(req.Context())
	if err != nil {
		writeErr(res, http.StatusInternalServerError, "list api keys: "+err.Error())
		return
	}
	rows := make([]apiKeyRow, 0, len(users))
	for _, u := range users {
		rows = append(rows, apiKeyRow{ID: u.ID, Name: u.Name, CreatedAt: u.CreatedAt})
	}
	writeJSON(res, http.StatusOK, map[string]any{"keys": rows})
}

type createAPIKeyRequest struct {
	Name string `json:"name"`
}

func (a *APIKeyService) create(res http.ResponseWriter, req *http.Request) {
	var body createAPIKeyRequest
	dec := json.NewDecoder(http.MaxBytesReader(res, req.Body, 1<<20))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&body); err != nil {
		writeErr(res, http.StatusBadRequest, "invalid JSON body: "+err.Error())
		return
	}
	name := strings.TrimSpace(body.Name)
	if name == "" {
		writeErr(res, http.StatusBadRequest, "name is required")
		return
	}

	id, token, err := a.Svc.Create(req.Context(), name)
	if err != nil {
		if errors.Is(err, store.ErrUserExists) {
			writeErr(res, http.StatusConflict, "user already exists: "+name)
			return
		}
		writeErr(res, http.StatusInternalServerError, "create api key: "+err.Error())
		return
	}

	writeJSON(res, http.StatusCreated, map[string]any{"id": id, "name": name, "token": token})
}

// remove deletes an API user by id, revoking its bearer token immediately.
// The service refuses to remove the "edge" console user and the
// currently-authenticated user.
func (a *APIKeyService) remove(res http.ResponseWriter, req *http.Request) {
	id, err := strconv.ParseInt(chi.URLParam(req, "id"), 10, 64)
	if err != nil || id <= 0 {
		writeErr(res, http.StatusBadRequest, "invalid user id")
		return
	}

	err = a.Svc.Delete(req.Context(), id)
	switch {
	case errors.Is(err, sql.ErrNoRows), errors.Is(err, store.ErrUserNotFound):
		writeErr(res, http.StatusNotFound, "api key not found")
	case errors.Is(err, service.ErrEdgeUserProtected):
		writeErr(res, http.StatusConflict, "the 'edge' user is required by the operator console and cannot be removed")
	case errors.Is(err, service.ErrSelfDelete):
		writeErr(res, http.StatusConflict, "cannot remove the API key you are currently authenticated with")
	case err != nil:
		writeErr(res, http.StatusInternalServerError, "delete api key: "+err.Error())
	default:
		res.WriteHeader(http.StatusNoContent)
	}
}
