package apikeys

import (
	"database/sql"
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"strings"

	"github.com/go-chi/chi/v5"

	"github.com/hazemarian/poor-man-stack/pmcluster/internal/store"
)

// HTTP exposes API-user (bearer token) management over the Bearer-protected
// /api router. The bearer token is generated by the service, hashed
// (argon2id) at rest, and returned to the caller ONCE on creation; listing
// users never reveals token material.
type HTTP struct {
	Svc Service
}

// Mount registers the /api/api_keys routes.
func (h *HTTP) Mount(r chi.Router) {
	r.Get("/api_keys", h.list)
	r.Post("/api_keys", h.create)
	r.Delete("/api_keys/{id}", h.remove)
}

type apiKeyRow struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	CreatedAt  int64  `json:"created_at"`
	LastUsedAt int64  `json:"last_used_at"`
}

func (h *HTTP) list(res http.ResponseWriter, req *http.Request) {
	keys, err := h.Svc.List(req.Context())
	if err != nil {
		writeErr(res, http.StatusInternalServerError, "list api keys: "+err.Error())
		return
	}
	rows := make([]apiKeyRow, 0, len(keys))
	for _, k := range keys {
		rows = append(rows, apiKeyRow(k))
	}
	writeJSON(res, http.StatusOK, map[string]any{"keys": rows})
}

type createAPIKeyRequest struct {
	Name string `json:"name"`
}

func (h *HTTP) create(res http.ResponseWriter, req *http.Request) {
	var body createAPIKeyRequest
	dec := json.NewDecoder(http.MaxBytesReader(res, req.Body, 1<<20))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&body); err != nil {
		writeErr(res, http.StatusBadRequest, "invalid JSON body: "+err.Error())
		return
	}
	name := strings.TrimSpace(body.Name)
	if name == "" {
		writeErr(res, http.StatusBadRequest, "name is required")
		return
	}

	id, token, err := h.Svc.Create(req.Context(), name)
	if err != nil {
		if errors.Is(err, store.ErrUserExists) {
			writeErr(res, http.StatusConflict, "user already exists: "+name)
			return
		}
		writeErr(res, http.StatusInternalServerError, "create api key: "+err.Error())
		return
	}

	writeJSON(res, http.StatusCreated, map[string]any{"id": id, "name": name, "token": token})
}

// remove deletes an API user by id, revoking its bearer token immediately.
// The service refuses to remove the "edge" console user and the
// currently-authenticated user.
func (h *HTTP) remove(res http.ResponseWriter, req *http.Request) {
	id, err := strconv.ParseInt(chi.URLParam(req, "id"), 10, 64)
	if err != nil || id <= 0 {
		writeErr(res, http.StatusBadRequest, "invalid user id")
		return
	}

	err = h.Svc.Delete(req.Context(), id)
	switch {
	case errors.Is(err, sql.ErrNoRows), errors.Is(err, store.ErrUserNotFound):
		writeErr(res, http.StatusNotFound, "api key not found")
	case errors.Is(err, ErrEdgeUserProtected):
		writeErr(res, http.StatusConflict, "the 'edge' user is required by the operator console and cannot be removed")
	case errors.Is(err, ErrSelfDelete):
		writeErr(res, http.StatusConflict, "cannot remove the API key you are currently authenticated with")
	case err != nil:
		writeErr(res, http.StatusInternalServerError, "delete api key: "+err.Error())
	default:
		res.WriteHeader(http.StatusNoContent)
	}
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

func writeErr(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]any{"error": msg})
}
